const etnia = [
  { key: 1, value: '汉族', label: '汉族' },
  { key: 2, value: '蒙古族', label: '蒙古族' },
  { key: 3, value: '回族', label: '回族' },
  { key: 4, value: '藏族', label: '藏族' },
  { key: 5, value: '维吾尔族', label: '维吾尔族' },
  { key: 6, value: '苗族', label: '苗族' },
  { key: 7, value: '彝族', label: '彝族' },
  { key: 8, value: '壮族', label: '壮族' },
  { key: 9, value: '布依族', label: '布依族' },
  { key: 10, value: '朝鲜族', label: '朝鲜族' },
  { key: 11, value: '满族', label: '满族' },
  { key: 12, value: '侗族', label: '侗族' },
  { key: 13, value: '瑶族', label: '瑶族' },
  { key: 14, value: '白族', label: '白族' },
  { key: 15, value: '土家族', label: '土家族' },
  { key: 16, value: '哈尼族', label: '哈尼族' },
  { key: 17, value: '哈萨克族', label: '哈萨克族' },
  { key: 18, value: '傣族', label: '傣族' },
  { key: 19, value: '黎族', label: '黎族' },
  { key: 20, value: '傈僳族', label: '傈僳族' },
  { key: 21, value: '佤族', label: '佤族' },
  { key: 22, value: '畲族', label: '畲族' },
  { key: 23, value: '高山族', label: '高山族' },
  { key: 24, value: '拉祜族', label: '拉祜族' },
  { key: 25, value: '水族', label: '水族' },
  { key: 26, value: '东乡族', label: '东乡族' },
  { key: 27, value: '纳西族', label: '纳西族' },
  { key: 28, value: '景颇族', label: '景颇族' },
  { key: 29, value: '柯尔克孜族', label: '柯尔克孜族' },
  { key: 30, value: '土族', label: '土族' },
  { key: 31, value: '达斡尔族', label: '达斡尔族' },
  { key: 32, value: '仫佬族', label: '仫佬族' },
  { key: 33, value: '羌族', label: '羌族' },
  { key: 34, value: '布朗族', label: '布朗族' },
  { key: 35, value: '撒拉族', label: '撒拉族' },
  { key: 36, value: '毛南族', label: '毛南族' },
  { key: 37, value: '仡佬族', label: '仡佬族' },
  { key: 38, value: '锡伯族', label: '锡伯族' },
  { key: 39, value: '阿昌族', label: '阿昌族' },
  { key: 40, value: '普米族', label: '普米族' },
  { key: 41, value: '塔吉克族', label: '塔吉克族' },
  { key: 42, value: '怒族', label: '怒族' },
  { key: 43, value: '乌孜别克族', label: '乌孜别克族' },
  { key: 44, value: '俄罗斯族', label: '俄罗斯族' },
  { key: 45, value: '鄂温克族', label: '鄂温克族' },
  { key: 46, value: '德昂族', label: '德昂族' },
  { key: 47, value: '保安族', label: '保安族' },
  { key: 48, value: '裕固族', label: '裕固族' },
  { key: 49, value: '京族', label: '京族' },
  { key: 50, value: '塔塔尔族', label: '塔塔尔族' },
  { key: 51, value: '独龙族', label: '独龙族' },
  { key: 52, value: '鄂伦春族', label: '鄂伦春族' },
  { key: 53, value: '赫哲族', label: '赫哲族' },
  { key: 54, value: '门巴族', label: '门巴族' },
  { key: 55, value: '珞巴族', label: '珞巴族' },
  { key: 56, value: '基诺族', label: '基诺族' },
  { key: 91, value: '其他族', label: '其他族' },
  { key: 92, value: '外国血统', label: '外国血统' },
  { key: 93, value: '外国民族', label: '外国民族' },
];

const gender = [
  {
    key: '男',
    label: '男',
    value: '男',
  },
  {
    key: '女',
    label: '女',
    value: '女',
  },
];

export default {
  gender,
  etnia,
};
